load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_binary(
    name = "cpp-asio-tcp-server",
    srcs = ["main.cpp"],
    deps = [
        "//third_party/asio",
        "//third_party/spdlog"
    ],
)

