# cpp-cross-platform/BUILD
load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "cpp-cross-platform",
    srcs = glob(["*.cpp", "*.h", "**/*.h"]),
    deps = [
        
    ],
    copts = ["--std=c++23"],
    linkopts = []
)
